name: Build

on: push

jobs:
  win-build:
    runs-on: windows-latest
    name: Windows Build

    steps:
      - uses: actions/checkout@v3

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Configure CMake
        shell: cmd
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -DDynamicBinaryInstrument=OFF -DPlugin.SymbolResolver=OFF -A x64 -B build64
          cmake -DCMAKE_BUILD_TYPE=Release -DDynamicBinaryInstrument=OFF -DPlugin.SymbolResolver=OFF -A Win32 -B build32

      - name: Build x86
        run: |
          msbuild -m -p:Configuration=Release -t:dobby build32/Dobby.sln

      - name: Build x64
        run: |
          msbuild -m -p:Configuration=Release -t:dobby build64/Dobby.sln

      - name: Collect artifacts
        shell: cmd
        run: |
          mkdir build_result
          copy "build32\Release\dobby.dll" "build_result\dobby_x86.dll"
          copy "build64\Release\dobby.dll" "build_result\dobby_x64.dll"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Windows
          path: build_result

  linux-build:
    runs-on: ubuntu-latest
    name: Linux Build

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -DDynamicBinaryInstrument=OFF -DPlugin.SymbolResolver=OFF -B build64
          cmake -DCMAKE_CXX_FLAGS="-m32" -DCMAKE_C_FLAGS="-m32" -DCMAKE_SHARED_LINKER_FLAGS="-m32" -DCMAKE_BUILD_TYPE=Release -DDynamicBinaryInstrument=OFF -DPlugin.SymbolResolver=OFF -B build86
          
      - name: Build x64
        run: |
          cd build64 && make dobby
          
      - name: Build x86
        run: |
          cd build86 && make dobby
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Linux
          path: |
            build64/*.so
            build86/*.so

          
  
